In [1]:
import pandas as pd


data1 = pd.read_csv('../raw/서울시 공원 (1인당 공원면적) 통계(2017).txt', sep ='\t',encoding='UTF8')
data2 = pd.read_csv('../raw/서울시 지역사회 건강통계(건강행태) 통계(2017).txt', sep ='\t',encoding='UTF8')
data3 = pd.read_csv('../raw/서울시 공원 통계(2017).txt', sep ='\t',encoding='UTF8')

In [2]:
data1.head()

,기간,자치구,공원(1인당공원면적),공원(1인당공원면적).1,공원(1인당공원면적).2,공원(1인당공원면적).3,공원(1인당공원면적).4,공원(1인당공원면적).5
0,기간,자치구,공원,공원,도시공원,도시공원,생활권 공원,생활권 공원
1,기간,자치구,면적,1인당공원면적,면적,1인당도시공원면적,면적,1인당생활권공원면적
2,2017,서울시,"168,374.6",16.6,"114,990.9",11.4,"55,627.6",5.5
3,2017,종로구,"11,569.7",70.4,"6,448.6",39.3,"3,055.9",18.6
4,2017,중구,"3,132.0",23.3,"3,082.4",22.9,"1,453.7",10.8

In [3]:
df1 = data1.drop([0,1])
df1 = df1.drop(['기간'],axis=1)
index1 = ['자치구','공원 면적', '1인당 공원 면적','도시공원 면적', '1인당 도시공원 면적','생활권 공원 면적', '1인당 생활권 공원 면적']
df1.columns = index1
df1 = df1.set_index("자치구")

In [4]:
df1

           공원 면적 1인당 공원 면적    도시공원 면적 1인당 도시공원 면적 생활권 공원 면적 1인당 생활권 공원 면적
자치구
서울시    168,374.6      16.6  114,990.9        11.4  55,627.6           5.5
종로구     11,569.7      70.4    6,448.6        39.3   3,055.9          18.6
중구       3,132.0      23.3    3,082.4        22.9   1,453.7          10.8
용산구      1,794.1       7.3      781.7         3.2   1,657.2           6.8
성동구      3,101.4       9.9    1,260.0           4   2,973.9           9.5
광진구      3,359.2         9    2,913.1         7.8   1,234.4           3.3
동대문구     1,275.6       3.5    1,033.5         2.8   1,192.5           3.3
중랑구      5,206.5      12.6    5,023.8        12.2   1,723.8           4.2
성북구      8,338.1      18.3    4,415.7         9.7   2,195.2           4.8
강북구     14,337.6      43.7    2,280.2           7   2,145.1           6.5
도봉구     10,083.6      29.1    1,165.9         3.4   1,276.2           3.7
노원구     14,337.7      25.7   13,850.2        24.8   2,794.1             5
은평구     13,997.9      28.5    6,228.9        12.7   1,251.8           2.6
서대문구     5,136.2      15.8    4,898.2        15.1   1,648.0           5.1
마포구      4,439.9      11.5    3,126.8         8.1   4,312.6          11.2
양천구      2,909.9       6.1    2,487.3         5.2   1,886.6             4
강서구      4,329.3       7.1    3,244.9         5.3   3,665.6             6
구로구      3,190.6       7.2    2,868.7         6.5   1,337.9             3
금천구      2,206.2       8.7    2,042.2         8.1     404.1           1.6
영등포구     3,092.6       7.7      746.1         1.9   2,966.0           7.4
동작구      4,585.7      11.2    4,391.7        10.8   3,123.9           7.7
관악구     10,975.7      21.1   10,969.2        21.1   1,282.7           2.5
서초구     15,883.2      35.7   15,079.8        33.9   2,287.0           5.1
강남구      6,591.7      11.8    5,302.0         9.5   3,565.4           6.4
송파구      4,445.7       6.6    1,837.7         2.7   4,222.8           6.3
강동구      3,384.6       7.7    2,842.4         6.5   1,971.2           4.5
서울대공원    6,670.0         -    6,670.0           -         -             -

In [5]:
data2.head()

,기간,지역,흡연,흡연.1,음주,음주.1,신체활동,신체활동.1,비만율,정신건강,정신건강.1,양호한 주관적 건강수준 인지율
0,기간,지역,현재흡연율,현재흡연자의 금연시도율,월간음주율,연간음주자의 고위험음주율,증등도 이상 신체활동 실천율,걷기실천율,비만율,스트레스 인지율,우울감 경험률,양호한 주관적 건강수준 인지율
1,2017,서울시,18.8,27.9,61,17.2,21.7,61,25.7,26.8,7.2,45.8
2,2017,종로구,16.5,30.9,59.5,19.4,21.4,51.2,25.8,24.1,5.3,45.5
3,2017,중구,19.1,15.7,54.4,15.7,23.1,66.6,24.5,24.8,5.2,46.1
4,2017,용산구,19.7,18.1,54.6,16.6,27.1,59.7,25.8,20.8,5.7,52.2

In [ ]:
df2 = data2.drop([0])
df2 = df2.drop(['기간','흡연','흡연.1','음주','음주.1'],axis=1)
index2=['자치구','증등도 이상 신체활동 실천율','걷기실천율','비만율','스트레스 인지율','우울감 경험률','양호한 주관적 건강수준 인지율']
df2.columns=index2
df2 = df2.set_index("자치구")

In [ ]:
df2

In [6]:
data3

,기간,자치구,계,계.1,계.2,자연공원,자연공원.1,자연공원.2,도시공원,도시공원.1,...,도시공원.20,도시공원.21,도시공원.22,도시공원.23,도시공원.24,도시공원.25,도시공원.26,기타공원,기타공원.1,기타공원.2
0,기간,자치구,계,계,계,자연공원,자연공원,자연공원,소계,소계,...,역사공원,수변공원,수변공원,생태공원,생태공원,가로공원,가로공원,기타공원,기타공원,기타공원
1,기간,자치구,공원수,(중복),면적,공원수,(중복),면적,공원수,(중복),...,면적,공원수,면적,공원수,면적,공원수,면적,공원수,(중복),면적
2,2017,합계,"2,837",33,"168,374.6",1,5,"37,345.0","2,183",25,...,500.9,12,116.8,1,51.5,8,22,653,3,"16,038.7"
3,2017,종로구,110,2,"11,569.7",-,1,"4,998.0",72,1,...,109.4,-,-,-,-,-,-,38,-,123.1
4,2017,중구,70,2,"3,132.0",-,-,-,59,2,...,26.2,-,-,-,-,-,-,11,-,49.6
5,2017,용산구,102,1,"1,794.1",-,-,-,65,1,...,23.9,-,-,-,-,2,3.5,37,-,"1,012.4"
6,2017,성동구,84,1,"3,101.4",-,-,-,63,1,...,-,-,-,-,-,3,8.8,21,-,"1,841.4"
7,2017,광진구,55,2,"3,359.2",-,-,-,41,1,...,-,-,-,-,-,-,-,14,1,446.1
8,2017,동대문구,96,1,"1,275.6",-,-,-,80,1,...,3.9,-,-,-,-,1,2.4,16,-,242.1
9,2017,중랑구,102,-,"5,206.5",-,-,-,65,-,...,-,-,-,-,-,-,-,37,-,182.7
10,2017,성북구,127,5,"8,338.1",-,1,"3,864.0",74,4,...,-,1,1.8,-,-,-,-,53,-,58.4
11,2017,강북구,83,1,"14,337.6",1,-,"11,899.0",63,1,...,-,-,-,-,-,-,-,19,-,158.4
12,2017,도봉구,79,2,"10,083.6",-,1,"8,703.0",51,1,...,-,-,-,1,51.5,-,-,28,-,214.7
13,2017,노원구,181,-,"14,337.7",-,-,-,129,-,...,-,-,-,-,-,-,-,52,-,487.4
14,2017,은평구,133,3,"13,997.9",-,1,"7,663.0",98,2,...,-,-,-,-,-,-,-,35,-,106
15,2017,서대문구,119,3,"5,136.2",-,1,218,78,2,...,-,-,-,-,-,-,-,41,-,20
16,2017,마포구,142,-,"4,439.9",-,-,-,98,-,...,4.8,-,-,-,-,-,-,44,-,"1,313.2"
17,2017,양천구,120,1,"2,909.8",-,-,-,102,1,...,-,-,-,-,-,-,-,18,-,422.6
18,2017,강서구,167,-,"4,329.3",-,-,-,155,-,...,-,-,-,-,-,-,-,12,-,"1,084.4"
19,2017,구로구,98,1,"3,190.6",-,-,-,56,1,...,-,-,-,-,-,2,7.3,42,-,321.9
20,2017,금천구,55,1,"2,206.2",-,-,-,47,1,...,-,-,-,-,-,-,-,8,-,164
21,2017,영등포구,126,-,"3,092.6",-,-,-,90,-,...,3,-,-,-,-,-,-,36,-,"2,346.5"
22,2017,동작구,83,1,"4,585.7",-,-,-,67,-,...,47.8,-,-,-,-,-,-,16,1,194
23,2017,관악구,110,2,"10,975.7",-,-,-,98,2,...,-,4,33.5,-,-,-,-,12,-,6.5
24,2017,서초구,151,-,"15,883.2",-,-,-,124,-,...,-,1,21.6,-,-,-,-,27,-,803.4
25,2017,강남구,155,2,"6,591.7",-,-,-,142,2,...,96.1,2,14.1,-,-,-,-,13,-,"1,289.7"
26,2017,송파구,164,1,"4,445.7",-,-,-,150,-,...,75.4,1,4.3,-,-,-,-,14,1,"2,608.0"
27,2017,강동구,124,1,"3,384.6",-,-,-,115,1,...,110.2,3,41.5,-,-,-,-,9,-,542.2
28,2017,서울대공원,1,-,"6,670.0",-,-,-,1,-,...,-,-,-,-,-,-,-,-,-,-

In [ ]:
df3 = pd.concat([df1,df2],axis=1, join='inner')

In [ ]:
df3

In [ ]:
def remove_comma(x):
    return x.replace(',', '')
df3['공원 면적'] = df3['공원 면적'].apply(remove_comma)
df3['도시공원 면적'] = df3['도시공원 면적'].apply(remove_comma)
df3['생활권 공원 면적'] = df3['생활권 공원 면적'].apply(remove_comma)

In [ ]:
df3 = df3.astype('float')

In [ ]:
import matplotlib as mp
import matplotlib.pyplot as plt
import seaborn as sns
fm = mp.font_manager.FontManager()

plt.rcParams['font.family'] = 'Malgun Gothic'

In [ ]:
plt.figure(figsize=(30,30))
plt.xticks(rotation=45)
sns.lineplot(data=df3)

In [ ]:
corr = df3.corr()

In [ ]:
corr

In [ ]:
sns.heatmap(corr)
plt.rc('axes', unicode_minus=False)
plt.show()

In [ ]:
df4 = df3[['1인당 공원 면적','걷기실천율']]

In [ ]:
plt.figure(figsize=(30,30))
plt.xticks(rotation=45)
sns.lineplot(data=df4)