In [4]:
import pandas as pd
import numpy as np

data_raw = pd.read_csv('../raw/지역사회건강조사 1차 전처리.csv')

In [5]:
df = data_raw[['만나이','성별','우울감 경험 여부','자치구']]

In [6]:
df_dep1=df[df['우울감 경험 여부'] != 9]
df_dep2=df_dep1[df_dep1['우울감 경험 여부'] != 7]
df_dep2

       만나이  성별  우울감 경험 여부  자치구
0       61   2          2  마포구
1       66   1          2  마포구
2       89   2          2  마포구
3       27   1          2  마포구
4       42   2          2  마포구
...    ...  ..        ...  ...
22925   62   2          2  금천구
22926   65   1          2  금천구
22927   24   1          2  금천구
22928   56   2          2  금천구
22929   66   2          2  금천구

[22909 rows x 4 columns]

In [7]:
data_pbhlth_code = pd.read_excel('../raw/지역사회건강조사 2019년 원시자료 이용지침서 등/지역사회건강조사 2019 원시자료 참고사항_보건소정보, 세대유형.xlsx',header=3)
data_pbhlth_code = data_pbhlth_code[data_pbhlth_code['시도코드'] == 11][['보건소코드','보건소명']]
data_pbhlth_code["보건소명"] = data_pbhlth_code["보건소명"].str.replace('보건소', '', regex=True)
data_pbhlth_code.columns=['보건소코드','자치구']
list_region = list(data_pbhlth_code.to_dict()['자치구'].values()) + ['서울시']
list_region.reverse()

In [8]:
list_df = []
for value in list_region:
    temp = df_dep2['자치구'] == value
    list_df.append(df_dep2[temp])
list_df[0] = df_dep2
list_df

[       만나이  성별  우울감 경험 여부  자치구
 0       61   2          2  마포구
 1       66   1          2  마포구
 2       89   2          2  마포구
 3       27   1          2  마포구
 4       42   2          2  마포구
 ...    ...  ..        ...  ...
 22925   62   2          2  금천구
 22926   65   1          2  금천구
 22927   24   1          2  금천구
 22928   56   2          2  금천구
 22929   66   2          2  금천구

 [22909 rows x 4 columns],
       만나이  성별  우울감 경험 여부   자치구
 6419   64   2          2  영등포구
 6420   23   1          2  영등포구
 6421   49   2          2  영등포구
 6422   51   1          2  영등포구
 6423   54   1          2  영등포구
 ...   ...  ..        ...   ...
 7330   25   2          2  영등포구
 7331   20   2          2  영등포구
 7332   51   2          2  영등포구
 7333   54   1          2  영등포구
 7334   26   1          2  영등포구

 [914 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 18346   64   2          2  양천구
 18347   68   1          2  양천구
 18348   66   1          2  양천구
 18349   62   2          2  양천구
 18350   66   1          2  양천구
 ...    ...  ..        ...  ...
 19256   84   2          2  양천구
 19257   60   1          2  양천구
 19258   61   2          2  양천구
 19259   27   2          2  양천구
 19260   63   2          2  양천구

 [915 rows x 4 columns],
      만나이  성별  우울감 경험 여부  자치구
 0     61   2          2  마포구
 1     66   1          2  마포구
 2     89   2          2  마포구
 3     27   1          2  마포구
 4     42   2          2  마포구
 ..   ...  ..        ...  ...
 912   75   1          2  마포구
 913   67   2          1  마포구
 914   62   1          2  마포구
 915   30   1          2  마포구
 916   29   2          2  마포구

 [917 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 11006   37   2          2  동작구
 11007   36   1          2  동작구
 11008   90   1          2  동작구
 11009   78   2          2  동작구
 11010   33   1          2  동작구
 ...    ...  ..        ...  ...
 11916   61   2          2  동작구
 11917   46   2          2  동작구
 11918   50   1          2  동작구
 11919   23   2          2  동작구
 11920   77   2          2  동작구

 [913 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 22014   42   2          2  금천구
 22015   43   1          2  금천구
 22016   71   2          2  금천구
 22017   41   1          2  금천구
 22018   77   2          2  금천구
 ...    ...  ..        ...  ...
 22925   62   2          2  금천구
 22926   65   1          2  금천구
 22927   24   1          2  금천구
 22928   56   2          2  금천구
 22929   66   2          2  금천구

 [916 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 19261   66   2          2  구로구
 19262   57   1          2  구로구
 19263   72   1          2  구로구
 19264   56   2          2  구로구
 19265   32   1          2  구로구
 ...    ...  ..        ...  ...
 20172   40   1          2  구로구
 20173   69   2          2  구로구
 20174   74   1          2  구로구
 20175   38   2          2  구로구
 20176   43   1          2  구로구

 [916 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 4588   57   2          2  관악구
 4589   58   2          2  관악구
 4590   68   1          2  관악구
 4591   74   1          2  관악구
 4592   69   2          2  관악구
 ...   ...  ..        ...  ...
 5499   79   2          2  관악구
 5500   63   2          2  관악구
 5501   34   1          2  관악구
 5502   72   1          2  관악구
 5503   32   1          2  관악구

 [916 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 11921   66   2          2  강서구
 11922   51   1          2  강서구
 11923   48   2          2  강서구
 11924   20   1          2  강서구
 11925   40   2          2  강서구
 ...    ...  ..        ...  ...
 12835   39   1          2  강서구
 12836   35   2          2  강서구
 12837   60   2          2  강서구
 12838   62   1          2  강서구
 12839   59   2          2  강서구

 [918 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 9173    49   2          2  중랑구
 9174    51   1          2  중랑구
 9175    27   1          2  중랑구
 9176    58   2          2  중랑구
 9177    75   1          2  중랑구
 ...    ...  ..        ...  ...
 10087   31   1          2  중랑구
 10088   31   2          2  중랑구
 10089   66   2          2  중랑구
 10090   73   2          2  중랑구
 10091   49   2          2  중랑구

 [917 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 10092   71   2          2  종로구
 10093   71   1          2  종로구
 10094   96   1          2  종로구
 10095   80   1          2  종로구
 10096   44   2          2  종로구
 ...    ...  ..        ...  ...
 11001   34   2          2  종로구
 11002   55   1          2  종로구
 11003   55   2          2  종로구
 11004   29   2          2  종로구
 11005   23   2          2  종로구

 [913 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 5504   38   2          2  은평구
 5505   31   1          2  은평구
 5506   59   2          2  은평구
 5507   31   1          2  은평구
 5508   58   1          2  은평구
 ...   ...  ..        ...  ...
 6414   43   2          2  은평구
 6415   45   1          2  은평구
 6416   78   1          2  은평구
 6417   69   2          2  은평구
 6418   47   2          2  은평구

 [915 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 1835   51   2          2  성북구
 1836   47   2          2  성북구
 1837   33   2          2  성북구
 1838   65   2          2  성북구
 1839   68   1          2  성북구
 ...   ...  ..        ...  ...
 2747   60   2          1  성북구
 2748   56   2          2  성북구
 2749   66   1          2  성북구
 2750   58   2          1  성북구
 2751   62   1          2  성북구

 [917 rows x 4 columns],
       만나이  성별  우울감 경험 여부   자치구
 2752   32   2          2  서대문구
 2753   29   1          2  서대문구
 2754   50   1          2  서대문구
 2755   74   2          2  서대문구
 2756   60   2          2  서대문구
 ...   ...  ..        ...   ...
 3663   21   2          2  서대문구
 3664   19   2          2  서대문구
 3665   76   2          1  서대문구
 3666   79   1          2  서대문구
 3667   77   2          2  서대문구

 [914 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 14673   59   2          2  도봉구
 14674   59   1          2  도봉구
 14675   75   2          2  도봉구
 14676   75   1          2  도봉구
 14677   51   2          2  도봉구
 ...    ...  ..        ...  ...
 15584   42   1          2  도봉구
 15585   22   1          2  도봉구
 15586   55   2          2  도봉구
 15587   33   2          2  도봉구
 15588   46   2          2  도봉구

 [916 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 917    24   1          2  노원구
 918    21   2          1  노원구
 919    26   1          2  노원구
 920    25   1          1  노원구
 921    27   1          2  노원구
 ...   ...  ..        ...  ...
 1830   42   2          1  노원구
 1831   42   1          2  노원구
 1832   61   2          2  노원구
 1833   33   1          2  노원구
 1834   31   2          2  노원구

 [914 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 20177   41   2          2  강북구
 20178   47   2          2  강북구
 20179   42   2          2  강북구
 20180   32   2          2  강북구
 20181   35   1          2  강북구
 ...    ...  ..        ...  ...
 21091   37   1          2  강북구
 21092   39   2          2  강북구
 21093   76   2          2  강북구
 21094   23   2          2  강북구
 21095   56   2          2  강북구

 [914 rows x 4 columns],
        만나이  성별  우울감 경험 여부 자치구
 12840   74   2          2  중구
 12841   80   1          2  중구
 12842   79   2          2  중구
 12843   52   2          2  중구
 12844   47   1          2  중구
 ...    ...  ..        ...  ..
 13751   37   2          2  중구
 13752   39   2          2  중구
 13753   33   1          2  중구
 13754   56   2          2  중구
 13755   58   1          2  중구

 [915 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 15589   52   2          2  용산구
 15590   62   2          2  용산구
 15591   85   2          2  용산구
 15592   72   2          2  용산구
 15593   22   2          2  용산구
 ...    ...  ..        ...  ...
 16503   53   2          2  용산구
 16504   24   2          2  용산구
 16505   21   1          2  용산구
 16506   51   2          2  용산구
 16507   78   1          2  용산구

 [919 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 8250   54   2          2  송파구
 8251   27   1          2  송파구
 8252   67   2          2  송파구
 8253   71   1          2  송파구
 8254   95   2          2  송파구
 ...   ...  ..        ...  ...
 9168   36   1          2  송파구
 9169   39   2          1  송파구
 9170   56   2          2  송파구
 9171   65   2          2  송파구
 9172   37   1          2  송파구

 [923 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 7335   66   2          2  성동구
 7336   22   2          1  성동구
 7337   25   2          2  성동구
 7338   67   1          2  성동구
 7339   60   2          2  성동구
 ...   ...  ..        ...  ...
 8245   38   2          2  성동구
 8246   41   1          2  성동구
 8247   40   1          2  성동구
 8248   62   1          2  성동구
 8249   59   2          2  성동구

 [915 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 17430   22   1          2  서초구
 17431   24   2          2  서초구
 17432   52   1          2  서초구
 17433   59   1          2  서초구
 17434   76   2          2  서초구
 ...    ...  ..        ...  ...
 18341   36   2          2  서초구
 18342   43   1          2  서초구
 18343   40   2          2  서초구
 18344   41   1          2  서초구
 18345   40   2          1  서초구

 [916 rows x 4 columns],
        만나이  성별  우울감 경험 여부   자치구
 13756   39   1          2  동대문구
 13757   38   2          2  동대문구
 13758   76   1          2  동대문구
 13759   63   2          2  동대문구
 13760   63   1          2  동대문구
 ...    ...  ..        ...   ...
 14668   34   2          2  동대문구
 14669   36   1          2  동대문구
 14670   53   2          2  동대문구
 14671   74   2          2  동대문구
 14672   74   2          2  동대문구

 [917 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 21096   67   2          2  광진구
 21097   70   1          2  광진구
 21098   33   2          2  광진구
 21099   22   2          2  광진구
 21100   22   2          2  광진구
 ...    ...  ..        ...  ...
 22009   35   1          2  광진구
 22010   36   2          2  광진구
 22011   39   1          2  광진구
 22012   25   1          2  광진구
 22013   55   2          2  광진구

 [917 rows x 4 columns],
       만나이  성별  우울감 경험 여부  자치구
 3668   79   1          2  강동구
 3669   73   2          2  강동구
 3670   41   2          2  강동구
 3671   31   2          2  강동구
 3672   82   2          2  강동구
 ...   ...  ..        ...  ...
 4583   38   2          2  강동구
 4584   57   2          2  강동구
 4585   58   1          2  강동구
 4586   69   1          2  강동구
 4587   59   2          2  강동구

 [920 rows x 4 columns],
        만나이  성별  우울감 경험 여부  자치구
 16508   53   1          1  강남구
 16509   54   2          2  강남구
 16510   49   2          2  강남구
 16511   47   2          2  강남구
 16512   27   1          2  강남구
 ...    ...  ..        ...  ...
 17425   35   2          2  강남구
 17426   79   2          2  강남구
 17427   69   1          2  강남구
 17428   64   2          2  강남구
 17429   40   2          2  강남구

 [922 rows x 4 columns]]

In [12]:
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

list_age = ['19~200','19~44','45~64','65~74','75~200']
list_sex = ['계','남','여']
idx_sex = []
idx_age = []
idx_region = []
value_dep = []
for i, value1 in enumerate(list_region):
    for j in list_age:
        for k in list_sex:            
            temp = list_df[i][list_df[i]['만나이']>=int(j.split('~')[0])]
            temp1 = temp[temp['만나이'] < int(j.split('~')[1])]
            if k == '남':
                temp2 = temp1[temp1['성별'] == 1]
            elif k == '여':
                temp2 = temp1[temp1['성별'] == 2]
            else:
                temp2 = temp1
            value_dep.append(round(100 - temp2['우울감 경험 여부'].value_counts(normalize = True)[2]*100,1))
            if j == '19~200':
                idx_age.append('계')
            elif j == '75~200':
                idx_age.append('75 이상')
            else:
                idx_age.append(j)
            idx_sex.append(k)
            idx_region.append(value1)

KeyError: 1

In [10]:
df1 = pd.DataFrame({'우울감 경험률':value_dep, '지역':idx_region,'연령별':idx_age,'성별':idx_sex})

df1 = df1.set_index(['지역','연령별','성별'])

df1

              우울감 경험률
지역  연령별   성별
서울시 계     계       6.3
          남       4.6
          여       7.7
    19~44 계       6.5
          남       4.9
...               ...
강남구 65~74 남       0.0
          여       5.5
    75 이상 계       8.3
          남       4.5
          여      10.5

[390 rows x 1 columns]

In [11]:
df1.to_csv("../raw/건강 데이터(우울감)_2019.csv", mode='w',encoding = 'utf-8-sig')